---
title: "R Assignment Simulations"
author: "Victoria Restivo"
date: '2018-11-28'
output: 
 html_document: 
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#1-Datacamp - completed course "Bioconductors"

#2-General simulator for diploids

##deterministic model
```{r}
p_t1 <- function(w_AA, w_aa, w_Aa, p_t0, q_t0) {
w_bar <- (((p_t0)^2)*w_AA) + (2 * p_t0 * q_t0 * w_Aa) + (((q_t0)^2)*w_aa)
p_t1 <- (((p_t0)^2)*(w_AA/w_bar)) + ((p_t0*q_t0)*(w_Aa/w_bar))
return(p_t1)
}

p_t1(w_AA = 1.0, w_aa = 1.0, w_Aa = 0.5, p_t0 = 0.5, q_t0 = 0.5)
```

##Multi-generation model
```{r}
diploid_selection <- function(p0 = 0.01, w1 = 1, w2 = 0.95, w3 = 0.9,  n = 500) {
    
    # Initialize vectors to store allele frequencies and mean pop fitness
    p <- rep(NA,n)  # a vector to store allele frequencies
    
    w_bar <- rep(NA, n)
     
    # starting conditions
   	p[1] <- p0 # starting allele frequencies

	  w_bar[1] <- (p[1]^2*w1) + ((2*p[1]*(1-p[1]))*w2) + ((1-p[1])^2)*w3
	
	
	# now we need to loop from generation to generation
	for ( i in 2:n) {
		w_bar[i - 1] <- (p[i-1]^2*w1) + ((2*p[i-1]*(1-p[i-1]))*w2) + ((1-p[i-1])^2)*w3 # mean population fitness
		p[i] <- ((p[i - 1]^2) * (w1/w_bar[i - 1])) + (p[i-1]*(1-p[i-1]))*(w2/w_bar[i-1])
	}
	  
    if (p > 0.9999) {
    fixation <- min(which.max(p > 0.9999))
    print("fixation for A1 occurs approximately at generation:", fixation )	
    } else {
        maxAlleleFreq <- max(p)
    	print("fixation of A1 does not occur, max. allele frequency is:", print(maxAlleleFreq, digits = 2) )
    }
	  
#plots
par(mfrow=c(2,2))
 
#change in allele frequency over time
plot(x = 1:n, y = p, 
     xlab="generations", 
	 ylab="Allele frequency (p)", 
	 pch = 20, col = "red", cex.lab = 1.5)

}

diploid_selection()
```

#Question 3
```{r}

genetic_drift_sim<- function(a, HD, ind, gen) {
  alleles <- c(sample(c("a", "A"), 
                      size = HD*(ind), 
                      replace = TRUE, 
                      prob = c(a, 1 - a)))

  allelefreq <- matrix(data = NA, nrow = gen, ncol = 2)

  for(i in 1:gen){
    alleles <- sample(alleles, HD*ind, replace=TRUE)
    allelefreq[i,2] <- (length(alleles[alleles =="A"]))/(HD*(ind))
    allelefreq[i,1] <- (length(alleles[alleles =="a"]))/(HD*(ind))
  }

 a <- allelefreq[,1]
 A <- allelefreq[,2]

 plot(1, type="n", xlim=c(1,gen), ylim=c(0,1), xlab="generation", ylab="Frequency Of Alleles")
 lines(x = A, type = "l", col = "red")
 lines(x = a, type = "l", col = "blue")
 legend("topleft", legend=c("A Frequency", "a Frequency"),
       col=c("red", "blue"), lty=1, cex=0.8)
}

genetic_drift_sim(0.5, 2, 20, 100)

```

#Question 4
```{r}
lost_allele <- function(A, gen, runs) {
  
A_prop1 <- matrix(data = NA, nrow = runs, ncol = 1)

for(j in 1:runs){
alleles <- c(sample(c("a", "A"), size = 400, replace = TRUE, prob = c(1 - A, A)))
A_prop <- integer()

for(i in 1:gen) {
alleles <- sample(alleles, 400, replace=TRUE)
A_freq <- (length(alleles[alleles =="A"]))/(400)
A_prop[i] <- A_freq
}

A_prop1[j,1] <- tail(A_prop, n = 1)
}

zerocount <- (length(which(A_prop1[,1] == "0")))
print(zerocount/runs)
}

lost_allele(0.1, 100, 1000)
```

#Question 5

##2 generations
```{r}
allele_counts <- sample(c("A", "a"), 
                        size=40,
                        replace=TRUE,
                        prob=c(0.5, 0.5))
allele_freq1 <- table(allele_counts)/length(allele_counts)

allele_freq1

allele_counts2 <- sample(c("A", "a"),
                         size=40,
                         replace=TRUE,
                         prob=allele_freq1)

allele_freq2 <- table(allele_counts2)/length(allele_counts2)

allele_freq2
``` 

##100 generations
```{r}
allele_trajectories <- function(A, gen, runs) {

plot(1, type="n", xlim=c(1,gen), ylim=c(0,1), xlab="Generation", ylab="Allele Frequency", main = "The Influence of Genetic Drift on Allele Frequencies")

for(j in 1:runs){
alleles <- c(sample(c("a", "A"), size = 400, replace = TRUE, prob = c(1 - A, A)))
Aprop <- integer()


for(i in 1:gen) {
alleles <- sample(alleles, 400, replace=TRUE)
Afreq <- (length(alleles[alleles =="A"]))/(400)
Aprop[i] <- Afreq
}
lines(x = Aprop, type = "l", col = sample(rainbow(n= runs)), lwd=2)

}

}

allele_trajectories(0.5, 100, 100)
```


#Question 6

```{r}
sig_pval <- function(a, b, lo, sd) {
x <- seq(from =1, to = 10, length.out=lo) 
y_deterministic <- a + b*x
y_simulated <- rnorm(length(x), mean = y_deterministic, sd)
mod_sim <- lm(y_simulated ~ x)

p_val_slope <- summary(mod_sim)$coef[2,4] 
p_val_slope
}

sig_pval(a=0.5, b=0.1, lo=20, sd=2)
# to confirm it works and you get the same answer every time, put set.seed(720) in the function
```

```{r}
# Run 1000 times
set.seed(720)
sig_pval <- function(a, b, lo, sd) {
x <- seq(from =1, to = 10, length.out=lo) 
y_deterministic <- a + b*x
y_simulated <- rnorm(length(x), mean = y_deterministic, sd)
mod_sim <- lm(y_simulated ~ x)

p_val_slope <- summary(mod_sim)$coef[2,4] 
p_val_slope
}

sig_pval(a=0.5, b=0.1, lo=20, sd=2)

thousand_times <- replicate(1000, sig_pval(a=0.5, b=0.1, lo=20, sd=2))
thousand_times

#Generate a histogram
par(mfrow = c(1,1))
hist(thousand_times, freq=F)
curve(dunif(x, 0, 1), 0, 1, add = T, col = "red", lwd = 2)
sum(thousand_times<0.05)
#There are 107 instances where the p-vaule is less than 0.05
```

```{r}

#Change slope to 0
set.seed(720)
sig_pval <- function(a, b, lo, sd) {
x <- seq(from =1, to = 10, length.out=lo) 
y_deterministic <- a + b*x
y_simulated <- rnorm(length(x), mean = y_deterministic, sd)
mod_sim <- lm(y_simulated ~ x)

p_val_slope <- summary(mod_sim)$coef[2,4] 
p_val_slope
}

sig_pval(a=0.5, b=0.1, lo=20, sd=2)
thousand_times <- replicate(1000, sig_pval(a=0.5, b=0, lo=20, sd=2))
thousand_times

par(mfrow = c(1,1))
hist(thousand_times, freq=F)
curve(dunif(x, 0, 1), 0, 1, add = T, col = "red", lwd = 2)
sum(thousand_times<0.05)

#There are 61 instances where the p-value is less than 0.05. By changing the slope to 0, there are fewer instances where the p-value < 0.05, this indicates that more points are found along the slope of 0.1 and less on the slope of 0, meaning the slope of 0.1 is more statistically significant. 

```



```{r}
#Using a for loop
set.seed(720)
pval_less0.05 <- function(a, b, sd){
  
pvals <- integer()
forplot <- matrix(data = NA, nrow = 19, ncol = 2)
n=10

for(j in 1:10000){

x <- seq(from =1, to = 10, length.out = n)
y_deterministic <- a + b*x
  
for(i in 1:100) {
y_simulated <-rnorm(length(x), mean = y_deterministic, sd)
mod_sim <- lm(y_simulated ~ x)
p_val_slope <- summary(mod_sim)$coef[2,4]
pvals[i] <- p_val_slope
}

pless0.05 <- which(pvals < 0.05) 
forplot[j,2] <- (length(pless0.05))/100
forplot[j,1] <- n
n =  n + 5
if( n > 100){ 
break
}
}
print(forplot)
plot( x = forplot[,1], y = forplot[,2], type = "p", xlab = "Sample Size", ylab = "Proportion of < 0.05", main = "Effect of Sample size on P Value Significance", col = "red", pch = 16)
}

pval_less0.05(0.5, 0.1, 1.5)
```



